### ISSUE TITLE
Explore XDM object generation from Mixins

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#100]
Possible approaches: 
- input: list of mixins, schema definition, mixin id
- extract supported base class for a mixin - profile, experience event
- evaluate naming, structure, required fields
- list all mixin ids from the org

**Comment by kevinlind** [comment]
I'm splitting this issue into two smaller issues:
1) this issue is to generate object code from a single mixin by supplying the mixin id
2) issue #114, generate object code for multiple mixins by supplying a schema id
