### ISSUE TITLE
Allow Empty xdm data

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-edge-ios#106]
The current Edge extension fast bails out when the xdm data is nil or empty. But for Offer Decisioning event, no xdm data is needed. 
So I propose to allow empty xdm data, but not allow nil (we still need nil to mark that the XMDSchema object is failed to be translated to data). 

@emdobrin @kevinlind, your thoughs?

**Comment by kevinlind** [comment]
Is there a way in either JAG or Konductor to filter out these offer decisioning events so they are not treated as experience events and passed to DCCS? Even if the client doesn't add XDM data, Konductor adds IP and user agent context data as XDM which when sent to DCCS will add records in customers' datasets. I think we should avoid that if these requests do not contain any XDM data.

**Comment by emdobrin** [comment]
@shalehaha I followed up on this question with the Edge team and even though the XDM data is not required from the caller perspective for the Offer Decisioning event, as Kevin also mentioned above this event is enriched with some XDM data and sent to AEP when enabled. In my opinion from the client side we should at least ensure that the xdm.eventType is populated in case we ever need to filter out the events in AEP based on the triggering operation.
That being said, do you think it is reasonable to keep this non-empty xdm restriction for this reason?

**Comment by emdobrin** [comment]
The other option would be to make eventType mandatory, but I would prefer to keep it as part of the xdm data map similar with other fields.

**Comment by shalehaha** [comment]
It works for now to always define an `eventType`.
