### ISSUE TITLE
Explore XDM object generation from Mixin list in Schema definition

### ISSUE THREAD

**Issue by kevinlind** [adobe/aepsdk-edge-ios#114]
This is a continuation of issue #100 , which added object generation from a single Mixin id.

Explore generating object code from Mixins where a Schema definition is provided.

Update `generate` command to supply a schema id but output the generated code from the mixins used in the schema.

**Comment by emdobrin** [comment]
Won't do at this time, we can reopen this task or create a new one if needed.
