### ISSUE TITLE
Move XDMSchema protocol to Core

### ISSUE THREAD

**Issue by swarna04** [adobe/aepsdk-edge-ios#170]
This will allow other Edge extensions to accept xdm data from customers adhering to this protocol instead of accepting a free-form dictionary [String: Any]

Example personalization API request
```
static func updatePropositions(for decisionScopes: [DecisionScope], with xdm: XDMSchema? = nil)
```

**Comment by emdobrin** [comment]
@swarna04 I think we can do this change in both iOS and Android, as long as we keep the same names and, for android, keep the same package as well.
The only item I know of that requires more investigation is making XDMSchema objc compatible. For now the xdm schema is supported in Swift and Android.

**Comment by emdobrin** [comment]
Update: we decided not to move these classes to Core for now, but new extensions such as the Personalization extension may still provide a way to pass in xdm and raw data as dictionaries as part of their APIs to be attached at the time of the request to Edge Network.
