### ISSUE TITLE
Pod Install --repo-update Fails with "Remote branch 5.0.3 not found in upstream origin"

### ISSUE THREAD

**Issue by ayushmahajan12** [adobe/aepsdk-edge-ios#505]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

When running the command pod install --repo-update in the iOS directory of my project, I am encountering the following error:

`warning: Could not find remote branch 5.0.3 to clone.
fatal: Remote branch 5.0.3 not found in upstream origin
Failed to install Pods:
  command failed with exit status 1 (pod "_1.15.2_" "update" "--no-repo-update"):
    [!] [Codegen] warn: using experimental new codegen integration
    [!] Error installing AEPEdge
    [!] /opt/homebrew/bin/git clone https://github.com/adobe/aepsdk-edge-ios.git /var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/d20241023-10432-fzshxw --template= --single-branch --depth 1 --branch 5.0.3
Retrying with pod repo update...
`

It appears the branch 5.0.3 does not exist in the remote repository, which is causing the pod installation to fail.

### Environment

OS: iOS
SDK(s): AEPEdge

### Steps to reproduce

1. Create a new React Native project.
2. Install npm dependencies.
3. Navigate to the iOS directory.
4. Run the command: pod install --repo-update.

### Current behavior

warning: Could not find remote branch 5.0.3 to clone.
fatal: Remote branch 5.0.3 not found in upstream origin
Failed to install Pods:
  command failed with exit status 1 (pod "_1.15.2_" "update" "--no-repo-update"):
    [!] [Codegen] warn: using experimental new codegen integration
    [!] Error installing AEPEdge
    [!] /opt/homebrew/bin/git clone https://github.com/adobe/aepsdk-edge-ios.git /var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/d20241023-10432-fzshxw --template= --single-branch --depth 1 --branch 5.0.3
Retrying with pod repo update...

<img width="1438" alt="Screenshot 2024-10-23 at 2 29 15 PM" src="https://github.com/user-attachments/assets/32db4b39-b436-43fa-a5c3-2d15df33b7db">

### Expected behavior

The pods should install successfully without any errors related to missing branches.

**Comment by linxkaa-tw** [comment]
Same issues with mine: https://github.com/adobe/aepsdk-edge-ios/issues/506

**Comment by emdobrin** [comment]
@ayushmahajan12 thanks for reporting, can you try again please? Let me know if you still see issues
