### ISSUE TITLE
AEPEdge 5.0.3 is missing from the remote origin

### ISSUE THREAD

**Issue by linxkaa-tw** [adobe/aepsdk-edge-ios#506]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

Hi, we're using `Bitrise` for deploying our app using flutter. We use the latest version of `flutter_aepedge: ^4.1.0` but as of today, we're getting this error from our bitrise script

```script
Installing AEPEdge (5.0.3)
[!] Error installing AEPEdge
[!] /opt/homebrew/bin/git clone https://github.com/adobe/aepsdk-edge-ios.git /var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/d20241023-6343-xupuv5 --template= --single-branch --depth 1 --branch 5.0.3
Cloning into '/var/folders/7l/rszmbrmd6tv4pg52z6ql_5rc0000gn/T/d20241023-6343-xupuv5'...
warning: Could not find remote branch 5.0.3 to clone.
fatal: Remote branch 5.0.3 not found in upstream origin
```

While per yesterday (23 Oct) we're still able to build the APK through bitrise
![image](https://github.com/user-attachments/assets/96c3197c-2954-42c6-89d8-2ee3b239897b)

Is there any specific version I could downgrade to? Because currently I notice now the version only up to `5.0.2`

### Environment

OS: iOS 17.5.1
SDK(s): flutter_aepcore: 4.0.2 ; flutter_aepedge: ^4.1.0
IDE: Xcode 15.2
Pod Version: 1.15.2

**Comment by emdobrin** [comment]
Hi @linxkaa-tw thanks for reporting, can you try again?

**Comment by linxkaa-tw** [comment]
Thankyou! Works now @emdobrin closing this issue :D
