### ISSUE TITLE
Configurable Edge endpoint for development testing

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#84]
Need to provide a way for developers to test with Edge pre-prod/integration. 

Proposed solution: expose a new configuration key for the Experience Edge testing environment only for development, that can be set using MobileCore.updateConfig API.
Edge extension reads this key from config and does the mapping to the correct endpoint. By default, if this key is not present or it is not one of the expected values, it falls back to prod.

This key will not be exposed in Launch UI.

e.g. "edge.environment" = String in ("prod", "pre-prod", "int")

**Comment by emdobrin** [comment]
@kevinlind @pfransenadb thoughts on this? This is pretty frequently used when testing new features in Experience Edge pre-prod/int.

**Comment by pfransenadb** [comment]
@emdobrin I'm fine with adding this key for the purpose you describe.  Makes sense to me.

**Comment by kevinlind** [comment]
@emdobrin I like this idea too. It will be useful in cases where a custom is asking for a fix/change in Edge and needs to verify it before Edge pushes it to production. For clarification, when you say "only for development", are you meaning the config key is only used when the Launch "build.environment" is "dev"?

**Comment by emdobrin** [comment]
@kevinlind  I mean only for development testing, when using MobileCore.updateConfig and not supported in the Edge Launch UI.
