### ISSUE TITLE
Investigate SPM integration for third party extensions development

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#89]
While migrating the Edge extension to dynamic framework, we noticed some issues when linking the AEPCore extensions to the third party extension through SPM.

SPM is supposed to pick the right format for dependencies (static/dynamic), however it seems like by default it select static
When the project includes both dynamic framework target and test targets (unit tests, test apps), and the test target links the dynamic framework I noticed the following error: 
Swift package product 'AEPRulesEngine' is linked as a static library by 'unitTests' and 'AEPCoreDynamic'. This will result in duplication of library code.
While we currently use cocoapods for declaring the core dependency in the Platform extension, we need to investigate if chaining multiple extensions is supported through SPM, e.g.: Rules Engine <- Core <- Platform <- Messaging and what is the best development setup we can use for interdependencies. 

Current core setup: Rules Engine is fetched through SPM and so linked as a static library. Other core extensions are referencing Core as dynamic framework since they are in the same repo&project.

Related threads: https://github.com/renaudjenny/Swift-Package-Manager-Static-Dynamic-Xcode-Bug

**Comment by emdobrin** [comment]
@shalehaha is this something you have on your list for core as well?

**Comment by shalehaha** [comment]
@emdobrin this is not on our list. Core is also facing a new problem today with rule engine included via SPM. There is a run time error when using the built xcframeworks. Will need to revisit whether we should change to use pod to include rules as well.

**Comment by shalehaha** [comment]
Just an update, Core has switched to use cocoapod to include Rules Engine.

**Comment by emdobrin** [comment]
Do we need to clarify that in core documentation or should the README be sufficient?
