### ISSUE TITLE
Edge extension sometimes ignores the first `Edge.sendEvent` call

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-edge-ios#93]
Have seen this behavior several times, not sure it is a bug in edge or core.

Log looks like:
```
2020-10-23 14:35:06.907835-0600 AEPSampleApp[51363:4032655] [AEP SDK TRACE - <ResponseCallbacksHandler>] Registering callback for Edge response with request event id E5B9B6E3-3262-47AF-BF0E-F658958CA52F.
2020-10-23 14:35:06.908206-0600 AEPSampleApp[51363:4032655] [AEP SDK TRACE - <EventHub:dispatch(event:)>] Event #18, id: E5B9B6E3-3262-47AF-BF0E-F658958CA52F name: AEP Request Event type: com.adobe.eventType.edge source: com.adobe.eventSource.requestContent data: Optional(["xdm": ["_atag": {
    length = 190;
    name = "lemon tree";
    playlist = lemon;
}, "eventType": music.view], "datasetId": ""]) timestamp: 2020-10-23 20:35:06 +0000 responseId: nil is dispatched.
```

Then if I call `Edge.sendEvent`  again, the new event will be handled by edge extension, but the first event is just ignored.

**Comment by shalehaha** [comment]
https://github.com/adobe/aepsdk-core-ios/issues/432

**Comment by emdobrin** [comment]
Once this issue is closed, we should re-enable
`FunctionalTests.IdentityStateFunctionalTests testSendEvent_withNoECIDInIdentityState_requestSentWithoutECID`
This test was disabled as it was failing with message:
```
XCTAssertFalse failed - Timed out waiting for network request(s) with URL https://edge.adobedc.net/ee/v1/interact and HTTPMethod POST, expected 1 but received 0
Test Case '-[FunctionalTests.IdentityStateFunctionalTests testSendEvent_withNoECIDInIdentityState_requestSentWithoutECID]' failed (3.223 seconds).
```

**Comment by emdobrin** [comment]
Fetched latest core dev-v3.0.0 and enabled the test. Tested locally by running the test ~150times with no failures, will keep an eye on it on CI for the future runs.

**Comment by nporter-adbe** [comment]
From @emdobrin 
>I enabled our test and ran it multiple times with no failure

Closing.
